### ISSUE TITLE
flex-box初体验

### ISSUE THREAD

**Issue by JerryWang1996** [JerryWang1996/jerrywangBlog#12]
------
style:
```css
        .container{                 /*第一条为默认值*/
            display: flex;          /*块级或内联容器     flex inline-flex*/
            flex-direction: row;    /*主轴方向      row row-reverse column column-reverse*/
            flex-wrap: nowrap;      /*是否换行      nowrap wrap wrap-reverse（从下往上换行）*/
          /*flex-flow: row nowrap;  flex-flex-direction和flex-wrap: nowrap结合体*/
            justify-content:flex-start;/*关于主轴的对齐方式 flex-start flex-end center space-between（两端对齐，项目之间的间隔相等） space-around（项目两侧的间隔相等）*/
            align-items:flex-start; /*关于交叉轴轴的对齐方式 stretch（未设高度填满容器） flex-start flex-end center baseline（项目的第一行文字的基线对齐）;*/
            align-content:flex-start;/*自动换行时 出现多条主轴的对齐方式 flex-start flex-end center space-between space-around stretch;*/

            width: 100%;
            height: 800px;
        }
        .containerSpan{             /*flex item*/
            order: 0; /*integer 默认为0 顺序 类似于z-index*/
            flex-basis: auto;/*一般为auto*/
            flex-grow: 0;/*放大比例*/
            flex-shrink: 1;/*缩小比例*/
            align-self: auto;/*允许单个项目有与其他项目不一样的对齐方式
                                        auto flex-start flex-end center baseline stretch;*/

            width: 180px;
            height: 180px;
            background-color: red;
            margin: 20px;
        }
        @media screen and (max-width: 800px){
            .container{
                display: inline-flex;
                flex-direction: column;
                flex-wrap:nowrap;
                justify-content: space-around;
                align-items: flex-start;
            }
            .containerSpan{
                background-color: blue;
            }
        }
```
------
html:
```html
<div class="container">
    <span class="containerSpan" style="align-self:center;"></span>
    <span class="containerSpan"></span>
    <span class="containerSpan"></span>
    <span class="containerSpan"></span>
    <span class="containerSpan"></span>
    <span class="containerSpan"></span>
    <span class="containerSpan"></span>
    <span class="containerSpan"></span>
    <span class="containerSpan"></span>
</div>
```
