### ISSUE TITLE
关于垂直居中的几种可行办法

### ISSUE THREAD

**Issue by JerryWang1996** [JerryWang1996/jerrywangBlog#26]
```html
<div class="container" style="background-color: #e8e8e8;">
	<div class="content" style="background-color: #ffffff;">垂直居中</div>
</div>
```
### 1.使用flex-box(弹性布局)
  为父级元素设置高度，当然都是相对于主轴方向为row，即flex-direction: row;来说，如果主轴方向为column的时候恰好相反
```css
.container{display:flex;align-items:center;height:200px;}
.content{}
```
  *此外，使用justify-content:center;还可以使子元素水平居中。
-----------------------------------2019-3-12-------------------------------------
对于flex布局，除了设置父元素justify-content:center;align-items:center;，还可以设置子元素的margin:auto;来实现居中（也需要设置父元素高度）
### 2.使用伪元素
  为父级元素添加伪元素并设置高度
```css
.container::after{display:inline-block;vertical-align:middle;content:''; height:200px;}
.content{display:inline-block;vertical-align:middle;}
```
### 3.使用table布局
```css
.container{display: table;height: 200px;padding: 50px;}
.content{width: 10px;height: 10px;background-color: red;display: table-cell;}
```
### 4.使用relative和translate
  原理为父级元素设置为relative，然后子元素设置为absolute。然后子元素top设置为50%，再运用translate将子元素上移自身高度的50%
```css
.container{position:relative;height:200px;}
.content{position:absolute;top:50%;-webkit-transform: translate(0,-50%); -ms-transform: translate(0,-50%);transform: translate(0,-50%);}
```

此外，关于水平居中，可以仿照如上四种方法实现。或者使用BFC实现。
