### ISSUE TITLE
clip-path制作环形倒计时

### ISSUE THREAD

**Issue by JerryWang1996** [JerryWang1996/jerrywangBlog#35]
### “一动不动”的倒计时
* 首先，使用css3绘图函数conic-gradient绘制锥形渐变，设置好颜色以及模糊，模糊主要是为了使颜色过渡变得平滑
```css
div {
  background-image: conic-gradient(#9ED110, #50B517, #179067, #476EAF, #9f49ac, #CC42A2, #FF3BA7, #FF5800, #FF8100, #FEAC00, #FFCC00, #EDE604);
  filter: blur(10px);
}
```
* 然后，使用遮罩为元素中心进行遮罩，圆形变为圆环
```css
div {
  background-image: conic-gradient(#9ED110, #50B517, #179067, #476EAF, #9f49ac, #CC42A2, #FF3BA7, #FF5800, #FF8100, #FEAC00, #FFCC00, #EDE604);
  -webkit-mask: radial-gradient(transparent 70px,#000 0);
  filter: blur(10px);
}
```
* 之后可以增加一个span元素来展示倒计时数字，这样一个静态的倒计时就完成了

### 使倒计时动起来
* 前边已经做好了静态样式的铺垫，接下来就要用到核心属性clip-path了，clip-path是用来制作各种形状的切图的属性
  * 第一个可选值circle(r at x y)，顾名思义在坐标为(x,y)处切一个半径为r的圆形
  * 第二个可选值ellipse(rx ry at x y)，同样顾名思义在左边为(x,y)处切一个x轴半径为rx，y轴半径为ry的椭圆
  * 第三个可选值inset(t r b l round l-t r-t r-b l-b)，顾名思义切一个上右下左分别为t r b l圆角为l-t r-t r-b l-b的图形，t r b l分别为相对各自边界的百分比或像素值
  * 第四个可选值polygon(x1 y1,x2 y2, ...)，意思是切一个由(x1,y1),(x2,y2)等点围成的图形
  * 值得注意的是x和y的起点在元素的左上角，右下角为100%，在开发中建议使用百分比确定位置，可以便于元素的缩放
* 在倒计时中我们采用第四个值polygon，每次找出需要显示的图形的路径，通过js控制css的自定义属性值来实现动态的倒计时，原理与昨天的css进度条同理

### 贴一个demo
```html
<style>
  body {
    width: 200px;
    margin: 50px auto;
  }
  #start {
    height: 30px;
  }
  #main {
    margin-top: 20px;
    --a: 50% 50%,50% 0,100% 0,100% 100%,0 100%,0 0,50% 0;
    width: 200px;
    height: 200px;
    border-radius: 50%;
    background-image: conic-gradient(#9ED110, #50B517, #179067, #476EAF, #9f49ac, #CC42A2, #FF3BA7, #FF5800, #FF8100, #FEAC00, #FFCC00, #EDE604);
    -webkit-mask: radial-gradient(transparent 70px,#000 0);
    filter: blur(10px);
    clip-path: polygon(var(--a));
    transition: clip-path 1s;
  }
  #num {
    position: absolute;
    top: 153px;
    left: 50%;
    transform: translateX(-50%);
    font-size: 70px;
  }
</style>
<button id="start">开始倒计时</button>
<div id="main"></div>
<span id="num">10</span>
<script>
  const pos = {
    '0': '50% 50%,50% 0,50% 0,50% 0,50% 0,50% 0,50% 0',
    '1': '50% 50%,50% 0,100% 0,100% -20%,100% -20%,100% -20%,100% -20%',
    '2': '50% 50%,50% 0,100% 0,100% 30%,100% 30%,100% 30%,100% 30%',
    '3': '50% 50%,50% 0,100% 0,100% 70%,100% 70%,100% 70%,100% 70%',
    '4': '50% 50%,50% 0,100% 0,100% 100%,90% 100%,90% 100%,90% 100%',
    '5': '50% 50%,50% 0,100% 0,100% 100%,50% 100%,50% 100%,50% 100%',
    '6': '50% 50%,50% 0,100% 0,100% 100%,20% 100%,20% 100%,20% 100%',
    '7': '50% 50%,50% 0,100% 0,100% 100%,0 100%,0 70%,0 70%',
    '8': '50% 50%,50% 0,100% 0,100% 100%,0 100%,0 40%,0 40%',
    '9': '50% 50%,50% 0,100% 0,100% 100%,0 100%,0 0,10% 0',
    '10': '50% 50%,50% 0,100% 0,100% 100%,0 100%,0 0,50% 0'
  }
  let start = document.querySelector('#start');
  let main = document.querySelector('#main')
  let num = document.querySelector('#num');
  let temp = 9;
  let timer = null;
  start.addEventListener('click',() => {
    run();
    timer = setInterval(run,1000);
  })
  const run = () => {
    if (temp === -1){
      clearInterval(timer)
      return ;
    }
    num.textContent = temp;
    main.style.setProperty('--a',pos[temp--])
  }
</script>
```
