### ISSUE TITLE
表格隔行样式

### ISSUE THREAD

**Issue by JerryWang1996** [JerryWang1996/jerrywangBlog#6]
```css
table>tbody>tr:nth-child(even){//偶数行样式
        
}
table>tbody>tr:nth-child(odd){//奇数行样式
       
}
.table > tbody > tr > td{
        vertical-align: middle;     //垂直居中
	text-alin: center;          //水平居中
}
```
